{
 "title": "Netflow Exporter Overview",
 "description": "Show a Summary from Netflow Exporter Devices",
 "tags": [
  "netflow",
  "nfcollector",
  "exporter",
  "overview"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Group By Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "nfExporter",
    "label": "Netflow Exporter",
    "query": "SHOW TAG VALUES from sum_proto WITH KEY=ExpHost"
   },
   {
    "name": "ProtoName",
    "label": "Protocol",
    "query": "SHOW TAG VALUES from sum_proto WITH KEY=ProtoName  WHERE ExpHost=~/^$nfExporter$/"
   },
   { "name": "TopVal", "label": "Top", "query": "5,10,20,50" }
  ]
 },
 "panels": [
  { "title": "NetFlow Exporter: $nfExporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "nfExporter" },
  {
   "title": "$ProtoName",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "repeat": "ProtoName",
   "yaxes": [
    { "format": "decbytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ProtoName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "query": "SELECT sum(\"Bytes\") AS \"Bytes\", sum(\"Packets\") AS \"Packets\" FROM \"sum_proto\" WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY time($__interval), \"ProtoName\" fill(0)",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Packets" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "ProtoName", "operator": "=~", "value": "/^$ProtoName$/" }
     ]
    }
   ]
  },
  {
   "title": "$ProtoName",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ProtoName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "query": "SELECT sum(\"Bytes\") AS \"Bytes\", sum(\"Packets\") AS \"Packets\" FROM \"sum_proto\" WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY time($__interval), \"ProtoName\" fill(0)",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Packets" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "ProtoName", "operator": "=~", "value": "/^$ProtoName$/" }
     ]
    }
   ]
  },
  {
   "title": "$ProtoName",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ProtoName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "query": "SELECT sum(\"Bytes\") AS \"Bytes\", sum(\"Packets\") AS \"Packets\" FROM \"sum_proto\" WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY time($__interval), \"ProtoName\" fill(0)",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Packets" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "ProtoName", "operator": "=~", "value": "/^$ProtoName$/" }
     ]
    }
   ]
  },
  {
   "title": "$ProtoName",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ProtoName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "query": "SELECT sum(\"Bytes\") AS \"Bytes\", sum(\"Packets\") AS \"Packets\" FROM \"sum_proto\" WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY time($__interval), \"ProtoName\" fill(0)",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Packets" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "ProtoName", "operator": "=~", "value": "/^$ProtoName$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Src Host",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sHost,TOP(\"sum\", $TopVal) FROM (SELECT SUM(Bytes) AS \"sum\"  FROM sum_proto WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY  sHost)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Dst Host",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT dHost,TOP(\"sum\", $TopVal) FROM (SELECT SUM(Bytes) AS \"sum\"  FROM sum_proto WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY dHost)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Protocol Usage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 11 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_ProtoName",
     "groupBy": [
      { "params": [ "ProtoName" ], "type": "tag" },
      { "params": [ "ExpHost" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "query": "SELECT sum(\"Bytes\") FROM \"sum_proto\" WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY \"ProtoName\" fill(null)",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "ProtoName", "operator": "=~", "value": "/^$ProtoName$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Src Port",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sPort,TOP(\"sum\", $TopVal) FROM (SELECT SUM(Bytes) AS \"sum\"  FROM sum_proto WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY sPort)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Dst Port",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT dPort,TOP(\"sum\", $TopVal) FROM (SELECT SUM(Bytes) AS \"sum\"  FROM sum_proto WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY dPort)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Src Country (City)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 18 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_sCouLo ($tag_sCit)",
     "groupBy": [
      { "params": [ "sCouLo" ], "type": "tag" },
      { "params": [ "sCit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "sCouLo", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "sCit", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "ProtoName", "operator": "=~", "value": "/^$ProtoName$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Dst Country (City)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 18 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_dCouLo ($tag_dCit)",
     "groupBy": [
      { "params": [ "dCouLo" ], "type": "tag" },
      { "params": [ "dCit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "dCouLo", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "dCit", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "ProtoName", "operator": "=~", "value": "/^$ProtoName$/" }
     ]
    }
   ]
  }
 ]
}