{
 "title": "Netflow Summary Overview",
 "description": "Netflow Summary Overview",
 "tags": [
  "netflow",
  "nfcollector",
  "exporter",
  "overview"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Group By Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "nfExporter",
    "label": "Netflow Exporter",
    "query": "SHOW TAG VALUES from sum_proto WITH KEY=ExpHost"
   },
   {
    "name": "ProtoName",
    "label": "Protocol",
    "query": "SHOW TAG VALUES from sum_proto WITH KEY=ProtoName  WHERE ExpHost=~/^$nfExporter$/"
   },
   { "name": "TopVal", "label": "Top", "query": "5,10,20,50" },
   {
    "name": "nfVersion",
    "label": "Netflow Version",
    "query": "SHOW TAG VALUES from sum_proto WITH KEY=NfVersion"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$nfExporter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "nfExporter",
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_NfVersion",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ExpHost" ], "type": "tag" },
      { "params": [ "NfVersion" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "query": "SELECT count(\"Version\") FROM \"sum_proto\" WHERE (\"ExpHost\" =~ /^$nfExporter$/) AND $timeFilter GROUP BY time($__interval), \"ExpHost\", \"NfVersion\" fill(null)",
     "select": [
      [
       { "params": [ "Version" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" }
     ]
    }
   ]
  },
  {
   "title": "Flow Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "Flow Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "select": [
      [
       { "params": [ "Version" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "NfVersion", "operator": "=~", "value": "/^$nfVersion$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Src Host",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sHost,TOP(\"sum\", $TopVal) FROM (SELECT SUM(Bytes) AS \"sum\"  FROM sum_proto WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY  sHost)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Dst Host",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT dHost,TOP(\"sum\", $TopVal) FROM (SELECT SUM(Bytes) AS \"sum\"  FROM sum_proto WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY dHost)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Protocol Usage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_ProtoName",
     "groupBy": [
      { "params": [ "ProtoName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "query": "SELECT sum(\"Bytes\") FROM \"sum_proto\" WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY \"ProtoName\" fill(null)",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "ProtoName", "operator": "=~", "value": "/^$ProtoName$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Src Port",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sPort,TOP(\"sum\", $TopVal) FROM (SELECT SUM(Bytes) AS \"sum\"  FROM sum_proto WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY sPort)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Dst Port",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT dPort,TOP(\"sum\", $TopVal) FROM (SELECT SUM(Bytes) AS \"sum\"  FROM sum_proto WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"ProtoName\" =~ /^$ProtoName$/) AND $timeFilter GROUP BY dPort)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "GEO Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Top Src Country (City)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 17 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_sCouLo ($tag_sCit)",
     "groupBy": [
      { "params": [ "sCouLo" ], "type": "tag" },
      { "params": [ "sCit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "query": "SELECT sum(\"Bytes\") AS \"alias\" FROM \"sum_proto_geo\" WHERE (\"ExpHost\" =~ /^$nfExporter$/ AND \"sCouLo\" =~ /.*/ AND \"sCit\" =~ /.*/) AND $timeFilter GROUP BY  \"sCouLo\", \"sCit\" fill(null)",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "sCouLo", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "sCit", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "Top Dst Country (City)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_dCouLo ($tag_dCit)",
     "groupBy": [
      { "params": [ "dCouLo" ], "type": "tag" },
      { "params": [ "dCit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "dCouLo", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "dCit", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  }
 ]
}